---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0d36024c7b3570265
    fsType: ext4  
